services:
  # 1. SQL Server (Publisher)
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PW}
      - MSSQL_AGENT_ENABLED=True
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - replica-data:/var/opt/mssql/replica
    networks:
      - lab-net

  # 1b. SQL Server (Subscriber)
  mssql-secondary:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_secondary
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PW}
      - MSSQL_AGENT_ENABLED=True
    ports:
      - "1434:1433"
    restart: always
    volumes:
      - replica-data:/var/opt/mssql/replica
    networks:
      - lab-net

  # 2. PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    ports:
      - "5433:5432"
    restart: always
    networks:
      - lab-net

  # 3. Oracle
  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: oracle_container
    environment:
      - ORACLE_PASSWORD=${ORACLE_PW}
    ports:
      - "1521:1521"
    restart: always
    networks:
      - lab-net

  # 4. MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PW}
    ports:
      - "27017:27017"
    restart: always
    networks:
      - lab-net

  # 5. Spark (Delta Lake Engine)
  spark:
    image: apache/spark:3.5.1
    container_name: spark_delta_engine
    environment:
      - SPARK_MODE=master
    volumes:
      - ./delta_warehouse:/opt/spark/work-dir # Apache uses a different internal path
    ports:
      - "8080:8080"
      - "4040:4040"
    networks:
      - lab-net

# Infrastructure Definitions
networks:
  lab-net:
    driver: bridge

volumes:
  replica-data: